version: "3.8"

networks:
  it-test-network:
    driver: bridge

services:
  app-it-test:
    build:
      context: .
      dockerfile: ./Dockerfile.it-test
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ktaxes?sslmode=disable
    depends_on:
      - postgres
    networks:
      - it-test-network

  postgres:
    image: postgres:16
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    networks:
      - it-test-network





