version: "3.8"
services:
  app_integration_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.it-test
    environment:
      - DATABASE_URL="host=localhost port=5432 user=postgres password=postgres dbname=ktaxes sslmode=disable"
      - PORT=8080
    volumes:
      - $PWD:/app
    depends_on:
      - postgres
    networks:
      - integration-test

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    networks:
      - integration-test

networks:
  integration-test:

