version: "3.8"

networks:
  e2e-test-network:
    driver: bridge

services:
  e2e-postman:
    image: postman/newman:6-alpine
    volumes:
      - ./postman:/postman
    command:
      run /postman/ktax.postman_collection.json
      -e /postman/ktax-e2e.postman_environment.json
      --working-dir /postman/files
    depends_on:
      - goapp
    networks:
      - e2e-test-network

  goapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ktaxes?sslmode=disable
      - ADMIN_USERNAME=adminTax
      - ADMIN_PASSWORD=admin!
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - e2e-test-network

  postgres:
    image: postgres:16
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - e2e-test-network





