version: "3.8"

networks:
  integration-test:
    driver: bridge

services:
  app_integration_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.it-test
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ktaxes?sslmode=disable
#    volumes:
#      - $PWD:/app
    depends_on:
      - postgres
    networks:
      - integration-test

  postgres:
    image: postgres:16
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    networks:
      - integration-test





