basePath: /
definitions:
  admin.Err:
    properties:
      message:
        type: string
    type: object
  admin.Input:
    properties:
      amount:
        minimum: 0
        type: number
    type: object
  admin.KReceiptDeduction:
    properties:
      kReceipt:
        type: number
    type: object
  admin.PersonalDeduction:
    properties:
      personalDeduction:
        type: number
    type: object
  tax.Allowance:
    properties:
      allowanceType:
        $ref: '#/definitions/tax.AllowanceType'
      amount:
        minimum: 0
        type: number
    type: object
  tax.AllowanceType:
    enum:
    - donation
    - k-receipt
    type: string
    x-enum-varnames:
    - AllowanceTypeDonation
    - AllowanceTypeKReceipt
  tax.Err:
    properties:
      message:
        type: string
    type: object
  tax.TaxInformation:
    properties:
      allowances:
        items:
          $ref: '#/definitions/tax.Allowance'
        type: array
      totalIncome:
        minimum: 0
        type: number
      wht:
        minimum: 0
        type: number
    required:
    - totalIncome
    type: object
  tax.TaxLevel:
    properties:
      level:
        type: string
      tax:
        type: number
    type: object
  tax.TaxResult:
    properties:
      tax:
        type: number
      taxLevel:
        items:
          $ref: '#/definitions/tax.TaxLevel'
        type: array
      taxRefund:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Sophisticated K-Tax API
  title: K-Tax API
  version: "1.0"
paths:
  /admin/deductions/k-receipt:
    post:
      consumes:
      - application/json
      description: Admin set k-receipt deduction
      parameters:
      - description: Amount to set personal deduction
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/admin.Input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.KReceiptDeduction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/admin.Err'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/admin.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/admin.Err'
      security:
      - BasicAuth: []
      summary: Admin set k-receipt deduction
      tags:
      - admin
  /admin/deductions/personal:
    post:
      consumes:
      - application/json
      description: Admin set personal deduction
      parameters:
      - description: Amount to set personal deduction
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/admin.Input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.PersonalDeduction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/admin.Err'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/admin.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/admin.Err'
      security:
      - BasicAuth: []
      summary: Admin set personal deduction
      tags:
      - admin
  /tax/calculations:
    post:
      consumes:
      - application/json
      description: Calculate tax
      parameters:
      - description: Amount to calculate tax
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/tax.TaxInformation'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tax.TaxResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/tax.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tax.Err'
      summary: Calculate tax
      tags:
      - tax
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
